### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by zJiaJun** [Manitary/WotLK-LogParser#1]
When run python3 main.py and File -> Parse a log
![image](https://github.com/Manitary/WotLK-LogParser/assets/8327535/50954b82-499d-48bd-b683-4509c25f2605)

```
➜  WotLK-LogParser git:(master) ✗ python3 main.py
/Users/zhujiajun/IdeaProjects/github/WotLK-LogParser/logs/WoWCombatLog.txt
QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
Unable to open data source file.
```
how to fix ,ty

**Comment by Manitary** [comment]
Should be fixed with 5381ad1886093f6b6ec1a23b55a56a2e45ae9af5 and e042cadd1d8d63a676fa3a63f5655dd44ee8956f.  
Should other problems arise feel free to open a new issue.

Keep in mind that I do not recommend to use this for actual log analysis:  
- If you are playing WoW Classic, [warcraftlogs.com](https://classic.warcraftlogs.com/) is the way to go.  
- This is still in a PoC stage. For example, only Naxxramas bosses are included, and the parsing itself is too slow for regular use. I do not have any plan to continue development, unless I have reasons to believe there is a sizeable demand for it.
